[workspace]
members = ["crates/prelude-xml-parser", "crates/prelude-parser-py"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
authors = ["Paul Sanders <paul@pbsdatasolutions.com>"]
homepage = "https://github.com/pbs-data-solutions/prelude-parser"
repository = "https://github.com/pbs-data-solutions/prelude-parser"

[workspace.dependencies]
chrono = { version = "0.4.45", features = ["serde"] }
pyo3 = "0.29.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
